name: Puppeteer Lighthouse
on: [push]

jobs:
  build:
    name: Puppeteer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
        working-directory: ./src
      - run: npm run main output/report.html
        working-directory: ./src
      - uses: actions/upload-artifact@master
        with:
          name: report file
          path: output/report.html
